name: Render and Lint Documentation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Current Go releases plus the versions in **/go.mod are tested.
        # See also BUILD_SPEC_MODULE_ONLY below.
        go: ['go.mod', 'schema/go.mod', 'oldstable', 'stable']
        # https://github.com/actions/setup-go/tree/v5#getting-go-version-from-the-gomod-file
        # https://github.com/actions/setup-go/tree/v5#using-stableoldstable-aliases

    name: Documentation and Linting
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ !endsWith(matrix.go, 'go.mod') && matrix.go || null }}
          go-version-file: ${{ endsWith(matrix.go, 'go.mod') && matrix.go || null }}
          cache-dependency-path: ./**/go.sum

      - name: Render and Lint
        env:
          # do not automatically upgrade go to a different version: https://go.dev/doc/toolchain
          GOTOOLCHAIN: local
          BUILD_SPEC_MODULE_ONLY: ${{ matrix.go == 'go.mod' }}
        run: |
          export PATH="$(go env GOPATH)/bin:$PATH"
          make install.tools
          go work init . schema
          go get -t -d ./...
          ls ../
          make
          make .gitvalidation
          make lint
          make check-license
          make test
          make docs

      - name: documentation artifacts
        uses: actions/upload-artifact@v4
        if: matrix.go == 'stable'
        with:
          name: oci-docs
          path: output

  security-scan:
    runs-on: ubuntu-latest
    name: Security Vulnerability Scan
    steps:
      - uses: actions/checkout@v4


      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: ./**/go.sum


      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest


      - name: Run govulncheck on root module
        run: govulncheck ./...


      - name: Run govulncheck on schema module
        run: |
          cd schema
          govulncheck ./...